Controllers/DisputasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Newtonsoft.Json;
using RpgMvc.Models;

namespace RpgMvc.Controllers
{
    public class DisputasController: Controller
    {
    public string uriBase = "xyz.somee.com/RpgApi/Personagens//";
    //xyz tem que ser subtituido pelo nome do seu site na API.

    [HttpGet]
    public async Task<ActionResult> IndexAsync()
    {
        try
        {
HttpClient httpClient = new HttpClient();
string token = HttpContext.Session.GetString("SessionTokenUsuario");
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

string uriBuscaPersonagnes = "http://xyz.somee.com/RpgApi/Personagens/GetAll";
HttpResponseMessage response = await httpClient.GetAsync(uriBuscaPersonagens);
string serialized = await response.Content.ReadAsStringAsync();

if (response.StatusCode == System.Net.HttpStatusCode.OK)
{
    List<PersonagensViewModel> listaPersonagens = await Task.Run(() => 
    JsonConvert.DeserializeObject<listaPersonagens<PersonagensViewModel>>(serialized));~

    ViewBag.ListaAtacantes = listaPersonagens;
    ViewBag.ListaOponentes = listaPersonagens;
    return View();
}
else
throw new System.Exception(serialized);
        }
        catch (System.Exception ex)
        {
            TempData["MensagemErro"] = ex.Message;
            return RedirectToAction("Index");
        }
    }  

    [HttpPost]
    public async Task<ActionResult> IndexAsync(DisputaViewModel disputa)
    {
        try
        {
            HttpClient httpClient = new HttpClient();
            string uriComplementar = "Arma";
            
            var content = new StringContent(JsonConvert.SerializeObject(disputa));
            content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = await httpClient.PostAsync(uriBase + uriComplementar, content);
            string serialized = await response.Content.ReadAsStringAsync();
            
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                disputa = await Task.Run(() => JsonConvert.DeserializeObject<DisputaViewModel>(serialized));
                TeamData["Mensagem"] = disputa.Narracao;
                return RedirectToAction("Index", "Personagens");
            }
            else
            throw new System.Exception(serialized);
                   }
                    catch (System.Exception ex)
        {
            TempData["MensagemErro"] = ex.Message;
            return RedirectToAction("Index");
        }
    }

    [HttpGet]
    public async Task<ActionResult> IndexHabilidadesAsync()
    {
        try
        {
HttpClient httpClient = new HttpClient();
string token = HttpContext.Session.GetString("SessionTokenUsuario");
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

string uriBuscaPersonagnes = "http://xyz.somee.com/RpgApi/Personagens/GetAll";
HttpResponseMessage response = await httpClient.GetAsync(uriBuscaPersonagens);
string serialized = await response.Content.ReadAsStringAsync();

if (response.StatusCode == System.Net.HttpStatusCode.OK)
{
    List<PersonagensViewModel> listaPersonagens = await Task.Run(() => 
    JsonConvert.DeserializeObject<listaPersonagens<PersonagensViewModel>>(serialized));~

    ViewBag.ListaAtacantes = listaPersonagens;
    ViewBag.ListaOponentes = listaPersonagens;
}    
else
throw new System.Exception(serialized);

string uriBuscaHabilidades = "http://xyz.somee.com/RpgApi/PersonagemHabilidades/GetHabilidades";
responde = await httpClient.GetAsync(uriBuscaHabilidades);
serialized = await response.Content.ReadAsStringAsync();

if (response.StatusCode == System.NetHttpSattusCode.OK)
{
List<HabilidadeViewModel> listaHabilidades = await Task.Run(() => 
JsonConvert.DeserializeObject<List<HabilidadeViewModel>>(serialized));
ViewBag.ListaHabilidades = listaHabilidades;
}
else
throw new System.Exception(serialized);

return View("IndexHabilidades");
        }
        catch (System.Exception ex)
        {
            TempData["MensagemErro"] = ex.Message;
            return RedirectToAction("Index");
        }
    }  
    }
}

Controllers/PersonagensController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RpgMvc.Models;

namespace RpgMvc.Controllers
{
    public class PersonagensController : Controller
    {
        public string uriBase = "http://lzsouza.somee.com/RpgApi/Personagens/";

        [HttpGet]
        public async Task<ActionResult> IndexAsync()
        {
            try
            {
                string perfil = HttpContext.Session.GetString("SessionPerfilUsuario");                
                ViewBag.Perfil = perfil;

                //string uriComplementar = (perfil == "Admin") ? "GetAll" : "GetByUser";
                //Caso ocorra erro na execução, comente a linha acima e descomente a linha abaixo
                string uriComplementar = "GetAll";

                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await httpClient.GetAsync(uriBase + uriComplementar);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    List<PersonagemViewModel> listaPersonagens = await Task.Run(() => JsonConvert.DeserializeObject<List<PersonagemViewModel>>(serialized));

                    return View(listaPersonagens);
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateAsync(PersonagemViewModel p)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                var content = new StringContent(JsonConvert.SerializeObject(p));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                HttpResponseMessage response = await httpClient.PostAsync(uriBase, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["Mensagem"] = string.Format("Personagem {0}, Id {1} salvo com sucesso!", p.Nome, serialized);
                    return RedirectToAction("Index");
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Create");
            }
        }

        [HttpGet]
        public async Task<ActionResult> DetailsAsync(int? id)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                HttpResponseMessage response = await httpClient.GetAsync(uriBase + id.ToString());
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    PersonagemViewModel p = await Task.Run(() =>
                    JsonConvert.DeserializeObject<PersonagemViewModel>(serialized));
                    return View(p);
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<ActionResult> EditAsync(int? id)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                HttpResponseMessage response = await httpClient.GetAsync(uriBase + id.ToString());

                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    PersonagemViewModel p = await Task.Run(() =>
                    JsonConvert.DeserializeObject<PersonagemViewModel>(serialized));
                    return View(p);
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> EditAsync(PersonagemViewModel p)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");

                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                var content = new StringContent(JsonConvert.SerializeObject(p));
                content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = await httpClient.PutAsync(uriBase, content);
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["Mensagem"] =
                        string.Format("Personagem {0}, classe {1} atualizado com sucesso!", p.Nome, p.Classe);

                    return RedirectToAction("Index");
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public async Task<ActionResult> DeleteAsync(int id)
        {
            try
            {
                HttpClient httpClient = new HttpClient();
                string token = HttpContext.Session.GetString("SessionTokenUsuario");
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                HttpResponseMessage response = await httpClient.DeleteAsync(uriBase + id.ToString());
                string serialized = await response.Content.ReadAsStringAsync();

                if (response.StatusCode == System.Net.HttpStatusCode.OK)
                {
                    TempData["Mensagem"] = string.Format("Personagem Id {0} removido com sucesso!", id);
                    return RedirectToAction("Index");
                }
                else
                    throw new System.Exception(serialized);
            }
            catch (System.Exception ex)
            {
                TempData["MensagemErro"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        




    }
}

Views/Personagens/Create.cshtml
@model RpgMvc.Models.PersonagemViewModel
@{
    ViewBag.Title = "Novo Personagem";
}

@if (@TempData["Mensagem"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Mensagem"]</div>
}
<!--Configuração para exibir mensagem de erro -->
@if (@TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["MensagemErro"]</div>
}

<h2>Criar um Novo Personagem</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />



        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

         <div class="form-group">
            @Html.LabelFor(model => model.Classe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                
                @Html.DropDownListFor(model => model.Classe , Html.GetEnumSelectList(typeof(RpgMvc.Models.Enuns.ClasseEnum)), 
                    "---Selecione---", new { @class = "form-control" })
            
            </div>
        </div>  

        <div class="form-group">
            @Html.LabelFor(model => model.PontosVida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.PontosVida, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Forca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Forca, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Inteligencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Inteligencia, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Defesa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Defesa, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <br/>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Retornar", "Index")
</div>

Views/Personagens/Details.cshtml
@model RpgMvc.Models.PersonagemViewModel
@{
    ViewBag.Title = "Detalhes do Personagem";
}
<h2>Detalhes do Personagem</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Id)</dt>
        <dd>@Html.DisplayFor(model => model.Id)</dd>

        <dt>@Html.DisplayNameFor(model => model.Nome)</dt>
        <dd>@Html.DisplayFor(model => model.Nome)</dd>    

        <dt>@Html.DisplayNameFor(model => model.Classe)</dt>
        <dd>@Html.DisplayFor(model => model.Classe)</dd>    

        <dt>@Html.DisplayNameFor(model => model.PontosVida)</dt>
        <dd>@Html.DisplayFor(model => model.PontosVida)</dd>    

        <dt>@Html.DisplayNameFor(model => model.Disputas)</dt>
        <dd>@Html.DisplayFor(model => model.Disputas)</dd>    

        <dt>@Html.DisplayNameFor(model => model.Vitorias)</dt>
        <dd>@Html.DisplayFor(model => model.Vitorias)</dd>    

        <dt>@Html.DisplayNameFor(model => model.Derrotas)</dt>
        <dd>@Html.DisplayFor(model => model.Derrotas)</dd>       

        <dt>@Html.DisplayNameFor(model => model.Forca)</dt>
        <dd>@Html.DisplayFor(model => model.Forca)</dd>              

        <dt>@Html.DisplayNameFor(model => model.Inteligencia)</dt>
        <dd>@Html.DisplayFor(model => model.Inteligencia)</dd>       

        <dt>@Html.DisplayNameFor(model => model.Defesa)</dt>
        <dd>@Html.DisplayFor(model => model.Defesa)</dd>          

    </dl>
</div>
<p>
    <!--@Html.ActionLink("Editar", "Edit", new { id = Model.Id}) |-->
    @Html.ActionLink("Retornar", "Index")
</p>

Views/Personagens/Edit.cshtml
@model RpgMvc.Models.PersonagemViewModel
@{
    ViewBag.Title = "Editar Personagem";
}

@if (@TempData["Mensagem"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Mensagem"]</div>
}
<!--Configuração para exibir mensagem de erro -->
@if (@TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["MensagemErro"]</div>
}

<h2>Editar dados do Personagem</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6"> @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control",
            @readonly = "readonly" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        
         <div class="form-group">
            @Html.LabelFor(model => model.Classe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.Classe , Html.GetEnumSelectList(typeof(RpgMvc.Models.Enuns.ClasseEnum)),
                    "----Selecione----", new { @class = "form-control"})
            </div>
        </div>
        
         <div class="form-group">
            @Html.LabelFor(model => model.PontosVida, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.PontosVida, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
         </div>
         <div class="form-group">
            @Html.LabelFor(model => model.Forca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Forca, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
         </div>
         <div class="form-group">
            @Html.LabelFor(model => model.Inteligencia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Inteligencia, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
         </div>
         <div class="form-group">
            @Html.LabelFor(model => model.Defesa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Defesa, new { htmlAttributes = new { @class = "form-control" } })                
            </div>
         </div>
          <br/>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Salvar alterações" class="btn btn-primary" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Retornar", "Index")
</div>

Views/Personagens/Index.cshtml
<!--Namespace da classe de Modelo para esta view-->
@model IEnumerable<RpgMvc.Models.PersonagemViewModel>

<!--Inclua os TempData para Sucesso e Erro aqui, conforme exemplo na view de Autenticação-->
@if (@TempData["Mensagem"] != null)
{
    <div class="alert alert-success" role="alert">
        @Html.Raw(@TempData["Mensagem"])</div>
}
<!--Configuração para exibir mensagem de erro -->
@if (@TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["MensagemErro"]</div>
}

@{ViewBag.Title = "Personagens"; }<!--Título da página para o navegador-->
<h2>Relação de Personagens</h2><!--Título da página-->
<p>
    <!--Links apontando para views na mesma pasta-->
    @Html.ActionLink("Criar Novo Personagem", "Create")
</p>
<table class="table table-striped">
    <thead>
    <tr class="table-primary"><!--Títulos das colunas da tabela-->        
        <th scope="col">@Html.DisplayNameFor(model => model.Id)</th>        
        <th scope="col">@Html.DisplayNameFor(model => model.Nome)</th>        
        <th scope="col">@Html.DisplayNameFor(model => model.Classe)</th>        
        <th scope="col">@Html.DisplayNameFor(model => model.PontosVida)</th>
        <th scope="col">@Html.DisplayNameFor(model => model.Disputas)</th>
        <th scope="col">@Html.DisplayNameFor(model => model.Vitorias)</th>
        <th scope="col">@Html.DisplayNameFor(model => model.Derrotas)</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    <!--Looping para escrever os dados na tabela-->
    @foreach (var item in Model)
    {
        <tr scope="row">
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Nome)</td>            
            <td>@Html.DisplayFor(modelItem => item.Classe)</td>   
            <td>@Html.DisplayFor(modelItem => item.PontosVida)</td>   
            <td>@Html.DisplayFor(modelItem => item.Disputas )</td> 
            <td>@Html.DisplayFor(modelItem => item.Vitorias)</td> 
            <td>@Html.DisplayFor(modelItem => item.Derrotas)</td>            
            <td><!--Coluna para Links/botões-->
                @Html.ActionLink("Editar", "Edit", new { id = item.Id } ) |
                @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                @Html.ActionLink("Deletar", "Delete", new { id = item.Id }, new { onclick = "return confirm('Deseja realmente deletar este personagem ?');"}) 
                @Html.ActionLink("Clique aqui para um embate com armas!!!", "Index", "Disputas", null, new { @class = "btn btn-warning"})
                @Html.ActionLink("Clique aqui para um embate com habilidades!!!", "IndexHabilidades", "Disputas", null, new {@class = "btn btn-dark"})
                
            </td>
        </tr>
    }    
    </tbody>
</table>